global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'logicus-prometheus'
    static_configs:
      - targets: ['logicus-prometheus:9090']

  - job_name: 'logicus-rabbitmq'
    static_configs:
      - targets: ['logicus-rabbitmq:15692']
